# apiVersion: v1

# kind: Service

# metadata:
#   name: sparta-node-service

# spec:
#   selector:
#     app: sparta-node-app
#   ports:
#   - port: 3000
#     targetPort: 3000

#   type: LoadBalancer


  # scale our app
  # hpa to autoscale our deployment on demand
  # in the config we need to declare min numbers of pods and max numbers of pods


# create a file called node-hpa.yml



#-----------------------------
  
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo-deployment
#   labels:
#     app: database
# spec:
#   clusterIP: None
#   selector:
#     app: database

# -----------------------------
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend